### ISSUE TITLE
Preview a serialized Graphviz graph in Visual Studio

### ISSUE THREAD

**Issue by takato1314** [aglasencnik/GraphvizVS#6]
**Is Your Feature Request Related to a Problem? Please Describe.**  
Hi, i am currently using the QuikGraph library to create a bidirectional graph in Graphviz format using [this approach](https://github.com/KeRNeLith/QuikGraph/wiki/Visualization-Using-Graphviz). When debugging, I am able to get the serialized graph in the correct format and able to display the entire graph in another [external visualizer](https://dreampuf.github.io/GraphvizOnline), so i am wondering if it's also possible to use your visualizer to display the same graph in Visual Studio 2022 as well?

**Describe the Solution You'd Like**  
Able to preview the serialized Graphviz graph using GraphvizVS visualizer.

**Describe Alternatives You've Considered**  
Currently, I am using this [online visualizer](https://dreampuf.github.io/GraphvizOnline) by copying out the string.

**Comment by aglasencnik** [comment]
Hi, basically how this extension works is, if you have a window open with .dot file extension (and have the preview window open from the View tool menu) and hit save, the graph appears in the preview window.

**Comment by takato1314** [comment]
Ah, ok that works. I didn't know that i have to open the .dot file and hit save once again. I'm not familiar with Visual Studio Extensions but would be a really nice enhancement if we could have visualized the dot graph string as well.
![image](https://github.com/aglasencnik/GraphvizVS/assets/10910968/ec2a2fce-b60d-4e62-963b-b7c02cb0be06)

At least at the moment, i could still export the .dot file first and open it in a window, just require a few more steps to save the file onto disk and reopen it again.

**Comment by aglasencnik** [comment]
Great idea! If I have time, I will add that.
